//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuncionesRol
    {
        public int ID { get; set; }
        public string NombreFun { get; set; }
        public int RolId { get; set; }
    
        public virtual UsuarioRol UsuarioRol { get; set; }
    }
}
