//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SalidaEmpleados
    {
        public int SalidaId { get; set; }
        public Nullable<int> EmpleadoId { get; set; }

        [Required(ErrorMessage = "Rellene el campo")]
        public string TipoSalida { get; set; }
        [Required(ErrorMessage = "Rellene el campo")]
        public string Motivo { get; set; }

        [Display (Name = "Fecha de Salida")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MMM/dd/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime FechaSalida { get; set; }
    
        public virtual Empleados Empleados { get; set; }
    }
}
